import FoundationOutlinedIcon from '@mui/icons-material/FoundationOutlined';
import FlightTakeoffOutlinedIcon from '@mui/icons-material/FlightTakeoffOutlined';
import AutoAwesomeOutlinedIcon from '@mui/icons-material/AutoAwesomeOutlined';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';

const histories = [
   {  
      generation: '1',
      icon: <FoundationOutlinedIcon variant='h5' sx={{ mb: '-3px' }} />,
      achievement: 'Foundation and Pioneering',
      chairman: 'In Hwoi Koo (1947-1969)',
      events: [
         { date: '1947.01', history: 'LuckyChemical Co., Ltd. is established (now LG Chem), Korea’s first cosmetics product “Lucky Cream” is produced', },
         { date: '1953.11', history: 'Lucky Industry is established (now LG International)', },
         { date: '1955.09', history: 'LuckyChemical Co., Ltd. starts to produce Lucky Toothpaste', },
         { date: '1956.05', history: 'LuckyChemical Co., Ltd. produces the first PVC pipe in Korea', },
         { date: '1958.10', history: 'Goldstar Co., Ltd. is established (now LG Electronics)', },
         { date: '1959.11', history: 'Goldstar Co., Ltd. produces the first Korean radio, A-501, bearing its trademark, Goldstar', },
         { date: '1960.03', history: 'Goldstar Co., Ltd. produces 12-inch fans for the first time in Korea', },
         { date: '1960.04', history: 'LuckyOil and Fat Co., Ltd. starts production of cosmetic and laundry soap including “Rainbow, Croba and Venus”', },
         { date: '1961.07', history: 'Goldstar Co., Ltd. produces the first automatic telephone in Korea', },
         { date: '1965.04', history: 'Goldstar Co., Ltd. produces the first domestic refrigerator', },
         { date: '1966.04', history: 'LuckyOil and Fat Co., Ltd. produces and sells synthetic detergents, “HiTi” for the first time in Korea', },
         { date: '1966.08', history: 'Goldstar Co., Ltd. produces the first 19-inch black and white TV in Korea', },
         { date: '1967.05', history: 'Honam Oil Refinery (now GS Caltex) holds inaugural general meeting', },
         { date: '1967.06', history: 'Goldstar Co., Ltd. produces the first FM/AM radios in Korea', },
         { date: '1967.07', history: 'LuckyOil and Fat Co., Ltd. develops and produces “Avon”, a liquid dishwashing detergent and “Cream Shampoo”, the first Korean shampoo', },
         { date: '1968.03', history: 'Goldstar Co., Ltd. produces the room air-conditioner in Korea', },
         { date: '1969.05', history: 'Goldstar Co., Ltd. establishes the semiconductor manufacturing company, Goldstar Electronics Co., Ltd.', },
         { date: '1969.05', history: 'Goldstar Co., Ltd. develops and produces the first Korean washing machine.', },
         { date: '1969.10', history: 'Goldstar Telecommunication is established', },
         { date: '1969.12', history: 'Lucky International is established', },
         { date: '1969.12', history: 'Yonam Culture Foundation is established (now the LG Yonam Foundation)', },
      ],
      imgs: [
         { url: '/images/lg/history/1stgen/cream.jpg', name: 'Cream', },
         { url: '/images/lg/history/1stgen/toothpaste.jpg', name: 'Toothpaste', },
         { url: '/images/lg/history/1stgen/radio.jpg', name: 'Radio', },
         { url: '/images/lg/history/1stgen/telephone.jpg', name: 'Telephone', },
         { url: '/images/lg/history/1stgen/detergent.jpg', name: 'Detergent', },
         { url: '/images/lg/history/1stgen/tv.jpg', name: 'TV', },
      ]
   },
   {
      generation: '2',
      icon: <FlightTakeoffOutlinedIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: 'Advancement and Innovation',
      chairman: 'Cha Kyung Koo (1970-1994)',
      events: [
         { date: '1972.12', history: 'LuckyChemical Co., Ltd. reaches 10 billion won in total sales', },
         { date: '1973.03', history: 'Goldstar Co., Ltd. develops and produces the first Korean cassette recorder', },
         { date: '1976.02', history: 'Goldstar Co., Ltd.’s TV production exceeds 1 million units', },
         { date: '1976.09', history: 'Lucky Co., Ltd. produces the first plastic windows and doors “Hi Chassis” in Korea', },
         { date: '1977.08', history: 'Goldstar Co., Ltd. starts mass production of 19-inch color TVs', },
         { date: '1978.03', history: 'Lucky Petrochemical Co., Ltd is established.', },
         { date: '1978.12', history: 'Lucky Co., Ltd.’s total revenue exceeds 100 billion won', },
         { date: '1981.05', history: 'Goldstar Co., Ltd. develops the first electronic VCR in Korea', },
         { date: '1981.08', history: 'Goldstar Semiconductor produces first domestic mini computers in Korea', },
         { date: '1982.05', history: 'Goldstar Co., Ltd. develops first color video camera in Korea', },
         { date: '1983.01', history: 'Name of Lucky Group is changed to Lucky Goldstar Group', },
         { date: '1984.02', history: 'Goldstar Semiconductor develops the first 8-bit microprocessor in Korea.', },
         { date: '1986.04', history: 'Lucky Economic Research Institute (now the LG Economic Research Institute) is established', },
         { date: '1987.10', history: 'Lucky Goldstar Twin Towers (now the LG Twin Towers) is constructed', },
         { date: '1990.02', history: '‘"Creating Values for Customers" and "People-oriented Management“ are adopted as management concepts', },
         { date: '1990.03', history: 'The LG Twins, a professional baseball team, is established', },
         { date: '1993.08', history: 'First Korean growth hormone “Utropin” is developed and commercialized', },         
      ],
      imgs: [
         { url: '/images/lg/history/2ndgen/cassette.jpg', name: 'Cassette', },
         { url: '/images/lg/history/2ndgen/chassis.jpg', name: 'Chassis', },
         { url: '/images/lg/history/2ndgen/colortv.jpg', name: 'Color TV', },
         { url: '/images/lg/history/2ndgen/vcr.jpg', name: 'VCR', },
         { url: '/images/lg/history/2ndgen/minicomputer.jpg', name: 'Minicomputer', },
         { url: '/images/lg/history/2ndgen/microprocessor.jpg', name: 'Microprocessor', },
      ]  
   },
   {
      generation: '3',
      icon: <AutoAwesomeOutlinedIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: 'Towards No.1 LG',
      chairman: 'Bon Moo Koo (1995-2017)',
      events: [
         { date: '1995.01', history: 'Name of Lucky Goldstar Group is changed to LG', },
         { date: '1996.07', history: 'LG Telecom (now LG U+) is established', },
         { date: '1999.08', history: 'LG Philips LCD (now LG Display) is established by LG LCD and Philips', },
         { date: '2001.04', history: 'LG Chem splits into three companies: LGCI, LG Chem and LG Household & Health Care', },
         { date: '2002.08', history: 'LG Life Sciences is established', },
         { date: '2003.04', history: 'LG Life Sciences’ “Factive” is marked as the first Korean drug approved by the U.S. FDA', },
         { date: '2003.10', history: `LG Philips LCD develops the world's first 55-inch HDTV LCD`, },
         { date: '2005.01', history: 'LG and GS are separated into two different groups', },
         { date: '2005.03', history: 'LG announces the “LG Way”', },
         { date: '2005.08', history: `LG Innotek develops the world's smallest 6.4 mm camera module for mobile phones`, },
         { date: '2006.03', history: `LG Philips LCD develops the world's largest 100-inch LCD`, },
         { date: '2009.04', history: 'LG Hausys is separated from LG Chem and launched independently', },
         { date: '2013.01', history: `LG Display produces World's First 55inch OLED TV`, },
         { date: '2015.07', history: 'LG Electronics releases Tromm Twin Wash', },
         { date: '2016.03', history: 'LG Electronics releases "LG Signature", super premium household appliances, in Korea', },
         { date: '2016.04', history: `“Eupenta”, made by LG Life Sciences, wins WHO PQ approval as Korea's first pentavalent vaccine`, },
         { date: '2017.11', history: `LG Innotek develops a UV-C LED with the world's highest output`, },
         { date: '2018.01', history: `LG Display develops world's first 88-inch 8K OLED display`, },
         { date: '2018.04', history: 'LG Science Park begins full operation', },
      ],  
      imgs: [
         { url: '/images/lg/history/3rdgen/pdptv.jpg', name: 'PDP TV', },
         { url: '/images/lg/history/3rdgen/factive.jpg', name: 'Drug', },
         { url: '/images/lg/history/3rdgen/cameramodule.jpg', name: 'Camera Module', },
         { url: '/images/lg/history/3rdgen/oled55fhd.jpg', name: 'OLED TV', },
         { url: '/images/lg/history/3rdgen/twinwash.jpg', name: 'Twinwash', },
         { url: '/images/lg/history/3rdgen/signiture.jpg', name: 'SIGNATURE', },
      ] 
   },
   {
      generation: '4',
      icon: <TrendingUpIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: 'The Future towards Customers 2018-',
      chairman: 'Kwang Mo Koo (2018 - )',
      events: [
         { date: '2019.12', history: 'LG Chem establishes an electric vehicle battery joint venture with GM of USA', },
         { date: '2020.10', history: "LG Electronics launches 'LG SIGNATURE OLED R', the world’s first rollable TV", },
         { date: '2020.12', history: "LG Chem Launches 'LG Energy Solution', a spin-off of Energy Solutions Company", },
         { date: '2020.12', history: "LG Launches 'LG AI Research', an artificial intelligence think tank", },
         { date: '2021.07', history: 'LG International, Pantos, LG Hausys, Silicon Works, LG MMA is separated from affiliates', },
         { date: '2021.12', history: `LG AI Research unveils the super-giant artificial intelligence(AI) model 'EXAONE'`, },
         { date: '2022.09', history: `LG Electronics Launches World's Largest 97 Type OLED TV`, },
      ],  
      imgs: [
         { url: '/images/lg/history/4thgen/rollableoled.jpg', name: 'Rollable TV', },
         { url: '/images/lg/history/4thgen/washtower.jpg', name: 'Washtower', },
         { url: '/images/lg/history/4thgen/tilda.jpg', name: 'TILDA', },
         { url: '/images/lg/history/4thgen/exaone.jpg', name: 'EXAONE', },
         { url: '/images/lg/history/4thgen/strechable.jpg', name: 'Strechable Display', },
         { url: '/images/lg/history/4thgen/standbyme.jpg', name: 'Standbyme', },
      ] 
   },
];

export default histories;
