export const itemTitles = {
   company: '会社',
   name: 'お名前',
   email: 'メールアドレス',
   mobile: '携帯電話',
   visitDate: '訪問日',
   visitTime: '訪問時間',
   deviceNo: '搬入物番号',
   device: '搬入物',
   purpose: '搬入目的',
   serial: 'シリアル番号',
   unsealed: 'ポート封印除外',
   reason: 'ポート封印除外の理由',
   wifi: 'Wi-Fi 接続',
   wirelessMAC: 'ワイヤレス MAC アドレス',
   cloudConnection: 'クラウドPC 接続',
   cloudIP: 'クラウドPC IPアドレス',
   cloudVMIP: 'クラウドPC VM IPアドレス',
   cloudConnectionIP: 'クラウドPC 接続 IPアドレス',
   conferenceRoomUse: '会議室の使用',
   people: '人数',
   startTime: '開始時間',
   endTime: '終了時間',
   laboratoryUse: '実験室使用',
   laboratory: '実験室選択',
   privacyCheck: 'プライバシーポリシー', 
   pledgeCheck: '訪問者の誓約',
};
