export const itemTitles = {
   company: 'Company',
   name: 'Name',
   email: 'Email Address',
   mobile: 'Mobile Phone',
   visitDate: 'Date of Visit',
   visitTime: 'Visiting Time',
   deviceNo: 'Device Number',
   device: 'Carrying-in Device',
   purpose: 'Purpose',
   serial: 'Serial Number',
   unsealed: 'Unsealed',
   reason: 'Unsealed Reason',
   wifi: 'Wi-Fi Connection',
   wirelessMAC: 'Wireless MAC Address',
   cloudConnection: 'Cloud PC Connection',
   cloudIP: 'Cloud PC IP Address',
   cloudVMIP: 'Cloud PC VM IP Address',
   cloudConnectionIP: 'Cloud PC Connection IP Address',
   conferenceRoomUse: 'Conference Room Use',
   people: 'Number of People',
   startTime: 'Start Time',
   endTime: 'End Time',
   laboratoryUse: 'Laboratory Use',
   laboratory: 'Laboratory',
   privacyCheck: 'Privacy Policy', 
   pledgeCheck: 'Visitor Pledge',
};
