import FoundationOutlinedIcon from '@mui/icons-material/FoundationOutlined';
import FlightTakeoffOutlinedIcon from '@mui/icons-material/FlightTakeoffOutlined';
import AutoAwesomeOutlinedIcon from '@mui/icons-material/AutoAwesomeOutlined';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';

const LGHistories = [
   {  
      generation: '1',
      period: '1947-1969',
      icon: <FoundationOutlinedIcon variant='h5' sx={{ mb: '-3px' }} />,
      achievement: '創業と開拓           ',
      mainImg: '/images/lg/lgHistory/1stgen/1stgen.jpg',
      meaning: '韓国の化学·電子産業の開拓時代',
      introTitle1: '歴史的な',
      introTitle2: '初の一歩',
      chairman: '具仁會',

      events: [
         { selected: true,  date: '1947.01', history: `ラッキー化学設立 (現LG Chem), 韓国初化粧品 'ラッキークリーム' 生産`, },
         { selected: false,  date: '1953.11', history: 'ラッキー産業設立 (現 LG 商社)', },
         { selected: true,  date: '1955.09', history: 'ラッキー化学、<ラッキー歯磨き粉>と<LUCKY></LUCKY>を商標登録し、歯磨き粉を本格生産、販売', },
         { selected: false,  date: '1956.05', history: 'ラッキー化学、韓国初ＰＶＣパイプ 生産', },
         { selected: false,  date: '1958.10', history: '金星社Goldstar (現LG Electronics) 設立', },
         { selected: true,  date: '1959.11', history: '金星社、<GoldStar>商標を添付した韓国初の国産ラジオ<A-501>生産', },
         { selected: false,  date: '1960.03', history: '金星社、韓国初の12インチ扇風機生産', },
         { selected: false,  date: '1960.04', history: 'ラッキー油脂工業 ＜虹、クローバー、ビーナス＞など化粧石鹸及び洗濯石鹸生産開始', },
         { selected: true,  date: '1961.07', history: '金星社、韓国初自動電話機生産', },
         { selected: false,  date: '1965.04', history: '金星社、国産冷蔵庫1号生産', },
         { selected: true,  date: '1966.04', history: 'ラッキー油脂工業、韓国初の合成洗剤＜ハイタイ＞、＜ニューヒート＞生産販売', },
         { selected: true,  date: '1966.08', history: '金星社, 韓国初の19インチ白黒テレビ生産', },
         { selected: false,  date: '1967.05', history: '湖南精油㈱(現GSカルテックス)創立総会、設立登記', },
         { selected: false,  date: '1967.06', history: '金星社,韓国初ＦＭ／ＡＭラジオ生産', },
         { selected: false,  date: '1967.07', history: 'ラッキー油脂工業、キッチン用液体洗剤<エヴォン>と国内初のシャンプー<クリームシャンプー>開発生産', },
         { selected: false,  date: '1968.03', history: '金星社, 韓国初ルームエアコンを生産', },
         { selected: false,  date: '1969.05', history: '金星社, 半導体生産会社である金星電子(株)設立', },
         { selected: false,  date: '1969.05', history: '金星社, 韓国初洗濯機開発生産', },
         { selected: false,  date: '1969.10', history: '金星通信設立', },
         { selected: false,  date: '1969.12', history: 'ラッキー商社設立', },
         { selected: false,  date: '1969.12', history: '蓮庵文化財団(現LG蓮庵文化財団)設立', },
      ],
      imgs: [
         { url: '/images/lg/lgHistory/1stgen/cream.jpg', name: 'クリーム', },
         { url: '/images/lg/lgHistory/1stgen/toothpaste.jpg', name: '歯磨き', },
         { url: '/images/lg/lgHistory/1stgen/radio.jpg', name: 'ラジオ', },
         { url: '/images/lg/lgHistory/1stgen/telephone.jpg', name: '電話', },
         { url: '/images/lg/lgHistory/1stgen/detergent.jpg', name: '洗剤', },
         { url: '/images/lg/lgHistory/1stgen/tv.jpg', name: 'テレビ', },
      ]
   },
   {
      generation: '2',
      period: '1970-1994',
      icon: <FlightTakeoffOutlinedIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: '前進と革新',
      mainImg: '/images/lg/lgHistory/2ndgen/2ndgen.jpg',
      chairman: '具滋暻',
      meaning: '先端技術開発と内実経営で成し遂げた高度成長期',
      introTitle1: '内実経営で',
      introTitle2: '財界の巨目になる',
      events: [
         { selected: false,  date: '1972.12', history: 'ラッキー化学、総売上高100億ウォンを突破', },
         { selected: true,  date: '1973.03', history: '金星社、 韓国初のカセットレコーダー開発生産', },
         { selected: false,  date: '1976.02', history: '金星社、テレビ生産100万台を突破', },
         { selected: true,  date: '1976.09', history: 'ラッキー, 韓国初の樹脂サッシ＜ハイサッシ＞生産', },
         { selected: true,  date: '1977.08', history: '金星社, 19インチカラーテレビ量産開始', },
         { selected: false,  date: '1978.03', history: 'ラッキー石油化学㈱設立', },
         { selected: false,  date: '1978.12', history: 'ラッキー, 総売上高1,000億ウォンを突破', },
         { selected: true,  date: '1981.05', history: '金星社, 韓国初の電子式VCR開発', },
         { selected: true,  date: '1981.08', history: '金星半導体、韓国初国産ミニコンピュータを生産', },
         { selected: false,  date: '1982.05', history: '金星社, 韓国初のカラービデオカメラの開発', },
         { selected: false,  date: '1983.01', history: '社名変更(ラッキー→ラッキー金星)', },
         { selected: true,  date: '1984.02', history: '金星半導体、韓国初の8bitマイクロプロセッサ開発', },
         { selected: false,  date: '1986.04', history: 'ラッキー経済研究所(現LG経済研究院)設立', },
         { selected: false,  date: '1987.10', history: 'ラッキー金星ツインタワー竣工 (現 LGツインタワー)', },
         { selected: false,  date: '1990.02', history: '「顧客のための価値創造」と「人間尊重の経営」経営理念宣言式', },
         { selected: false,  date: '1990.03', history: 'LGツインズプロ野球団創立', },
         { selected: false,  date: '1993.08', history: 'ラッキー、韓国初の成長ホルモン剤「ユートロピン」の開発及び商品化', },
      ],
      imgs: [
         { url: '/images/lg/lgHistory/2ndgen/cassette.jpg', name: 'カセット', },
         { url: '/images/lg/lgHistory/2ndgen/chassis.jpg', name: 'シャーシ', },
         { url: '/images/lg/lgHistory/2ndgen/colortv.jpg', name: 'カラーテレビ', },
         { url: '/images/lg/lgHistory/2ndgen/vcr.jpg', name: 'VCR', },
         { url: '/images/lg/lgHistory/2ndgen/minicomputer.jpg', name: 'ミニコンピューター', },
         { url: '/images/lg/lgHistory/2ndgen/microprocessor.jpg', name: 'マイクロプロセッサ', },
      ]  
   },
   {
      generation: '3',
      period: '1995-2017',
      icon: <AutoAwesomeOutlinedIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: '一等LGに向けて',
      mainImg: '/images/lg/lgHistory/3rdgen/3rdgen.jpg',
      chairman: '具本茂',
      meaning: "21世紀'超優良LG'に向けた跳躍の時期",
      introTitle1: '21世紀に向けた',
      introTitle2: '大革新',
      events: [
         { selected: false,  date: '1995.01', history: 'グループ名をLGに変更', },
         { selected: false,  date: '1996.07', history: 'LG Telecom (現LGU+) 設立', },
         { selected: false,  date: '1999.08', history: 'LG LCD、Philips社と合弁、LG.Philips LCD (現LG Display) 設立', },
         { selected: false,  date: '2001.04', history: 'LG Chem、3社(LGCI、LG Chem、LG生活健康)に分離', },
         { selected: false,  date: '2002.08', history: 'LG生命科学設立', },
         { selected: true,  date: '2003.04', history: 'LG生命科学<ファクティブ>、韓国初の米FDA新薬承認獲得', },
         { selected: false,  date: '2003.10', history: `LG Philips LCD、世界初の55インチHDTV用LCDを開発`, },
         { selected: false,  date: '2005.01', history: 'LG、GSと系列分離完了', },
         { selected: false,  date: '2005.03', history: 'LG Way宣言', },
         { selected: true,  date: '2005.08', history: 'LG Innotek、世界最小6.4mm携帯電話カメラモジュール開発', },
         { selected: false,  date: '2006.03', history: 'LG Philips LCD、世界最大100インチLCDを開発', },
         { selected: false,  date: '2009.04', history: 'LG Hausys、LG化学から分離して公式発足', },
         { selected: true,  date: '2013.01', history: 'LG Display、 世界初55インチOLED TV制作', },
         { selected: true,  date: '2015.07', history: 'LG Electronics、Tromm Twin Wash発売', },
         { selected: true,  date: '2016.03', history: `LG Electronics、超プレミアム家電'LGシグネチャー'韓国発売`, },
         { selected: false,  date: '2016.04', history: 'LG生命科学、韓国初の開発5価混合ワクチン<ユーペンタ> WHO PQ承認', },
         { selected: false,  date: '2017.11', history: 'LG Innotek、世界最高出力UV-C LED開発', },
         { selected: false,  date: '2018.01', history: 'LG Display、世界初の88インチ8K OLEDディスプレイ開発', },
         { selected: false,  date: '2018.04', history: 'LG Science Park本格稼働', },
      ], 
      imgs: [
         { url: '/images/lg/lgHistory/3rdgen/pdptv.jpg', name: 'PDPテレビ', },
         { url: '/images/lg/lgHistory/3rdgen/factive.jpg', name: '薬', },
         { url: '/images/lg/lgHistory/3rdgen/cameramodule.jpg', name: 'カメラモジュール', },
         { url: '/images/lg/lgHistory/3rdgen/oled55fhd.jpg', name: 'OLEDテレビ', },
         { url: '/images/lg/lgHistory/3rdgen/twinwash.jpg', name: 'ツインウォッシュ', },
         { url: '/images/lg/lgHistory/3rdgen/signiture.jpg', name: 'SIGNATURE', },
      ] 
   },
   {
      generation: '4',
      period: '2018-',
      icon: <TrendingUpIcon variant='h5'  sx={{ mb: '-3px' }} />,
      achievement: '顧客に対する未来',
      mainImg: '/images/lg/lgHistory/4thgen/4thgen.jpg',
      chairman: '具光謨 ',
      meaning: '顧客感動を最優先にした嬉しい挑戦',
      introTitle1: '新しい飛躍のための',
      introTitle2: '大胆な挑戦',
      events: [
         { selected: false,  date: '2019.12', history: 'LG Chem、米国GMと電気自動車バッテリー合弁法人設立', },
         { selected: true,  date: '2020.10', history: `LG ELectronics、世界初'LG SIGNATURE OLED R'リリース`, },
         { selected: false,  date: '2020.12', history: 'LG Chem、バッテリー事業、「LGエナジーソリューション」発足', },
         { selected: true,  date: '2020.12', history: 'LG、人工知能シンクタンク「LG AI研究院」発足', },
         { selected: false,  date: '2021.07', history: 'LG商社・パントス・LGハウシス・シリコンワークス・LG MMAなど5社の系列会社LXに系列分離、社名変更', },
         { selected: true,  date: '2021.12', history: 'LG AI研究院、超巨大AI「EXAONE(Expert AI for everyone、エクサワン)」公開', },
         { selected: false,  date: '2022.09', history: 'LG ELectronics、世界最大97型OLED TVを発売', },
      ],   
      imgs: [
         { url: '/images/lg/lgHistory/4thgen/rollableoled.jpg', name: 'Rollable TV', },
         { url: '/images/lg/lgHistory/4thgen/washtower.jpg', name: 'ウォッシュタワー', },
         { url: '/images/lg/lgHistory/4thgen/tilda.jpg', name: 'TILDA', },
         { url: '/images/lg/lgHistory/4thgen/exaone.jpg', name: 'EXAONE', },
         { url: '/images/lg/lgHistory/4thgen/strechable.jpg', name: 'Strechable Display', },
         { url: '/images/lg/lgHistory/4thgen/standbyme.jpg', name: 'Standbyme', },
      ] 
   },
];

export default LGHistories;
